ALTER TABLE `movies_ref`
  ADD COLUMN `slug` VARCHAR(255) NULL,
  ADD COLUMN `is_public` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX `slug` ON `movies_ref`(`slug`);

ALTER TABLE `users`
  ADD COLUMN `is_public` TINYINT(1) NOT NULL DEFAULT 0;
