name: Cinevault CI/CD  # El nombre que verás en la pestaña 'Actions' de GitHub.

on:                    # ¿CUÁNDO se debe ejecutar este asistente?
  push:                # Cuando alguien sube código...
    branches: [ "main" ] # ...específicamente a la rama principal.
  pull_request:        # O cuando alguien propone un cambio (PR).
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io      # El "almacén" donde guardaremos la imagen (GitHub Container Registry).
  IMAGE_NAME: ${{ github.repository }} # Usa tu nombre de usuario/proyecto (ej: juan/cinevault).

jobs:
  build-and-scan:      # Nombre del trabajo.
    runs-on: ubuntu-latest # GitHub nos presta una PC con Linux Ubuntu para hacer esto.
    permissions:       # Permisos que necesita el asistente:
      contents: read   # Leer tu código.
      packages: write  # Escribir (guardar) la imagen en el almacén de GitHub.

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # El asistente descarga tu código a la PC de GitHub.

      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # Tu nombre de usuario de GitHub.
          password: ${{ secrets.GITHUB_TOKEN }} # Contraseña temporal automática.

      - name: Build de la imagen (Local)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # NO la subimos todavía, primero queremos ver si es segura.
          load: true  # La deja lista en la PC de GitHub para el siguiente paso.
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test

      - name: Escaneo de Seguridad (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
          severity: 'CRITICAL,HIGH' # Solo detente si encuentras algo MUY grave.
          exit-code: '1' # SI HAY ERRORES, FALLA EL WORKFLOW (pone la X roja).
          ignore-unfixed: true

      - name: Push de la imagen
        if: github.event_name != 'pull_request' # Solo sube si es un push real a main (no una prueba).
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # ¡AHORA SÍ! Súbela al almacén.
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}